//This file has to be deleted later
const Sequelize = require('sequelize')
const User = require('./User')
const UserToken = require('./UserToken')
const Mcq = require('./mcq')
const Jumbled_sentence = require('./jumbled_sentence')
const Sentence_matching = require('./sentence_matching')
const Fill_in_the_blanks = require('./fill_in_the_blanks')
const Word_To_Picture = require('./word_picture')
const dictionary = require('./dictionary')
const flashcard = require('./flashcard')
const admin = require('./admin')
